# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bcd700603a0aecf41f2ad209f073b919a27f8e199e2fa6386e6b9375e06e3ceb3e754bc132773e74663aec089ed742452c50bbeaa4c365d8e2511faefe02a5e

test:
  secret_key_base: 9dcf6182efd2d1b215baee082255b0e7d60b595ee1632f23eade56c296ecfb03eaf2e0c478b11bea4b0b23a722eca0af221ec1a486e68c652505f3a56a154f80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
